#include <stdio.h>
#include <conio.h>
#include <iostream.h>

	main()
   {
   int a,b,c,d,e,f;
   cout <<"  Masukan Nilai 1:";cin>>a;
   cout <<"  Masukan Nilai 2:";cin>>b;
   cout <<"  Masukan Nilai 3:";cin>>c;
   d=a+b*c;
   e=a+(b*c);
   f=(a+b)*c;


	clrscr();

   cout <<"=======================\n";
   cout  <<"      NILAI AKHIR      \n";
   cout <<"=======================\n";
   cout <<"\n    HASIL AKHIR     :"<<d<<endl;
   cout <<"\n    HASIL AKHIR     :"<<e<<endl;
   cout <<"\n    HASIL AKHIR     :"<<f<<ends;
   getch();
   }
